#  =========== 宙斯物联网采集分析基础平台 ===========
server:
  port: 9090
  max-http-header-size: 10240
  shutdown: graceful
  undertow:
    threads:
      worker: 256
    buffer-size: 1024
    direct-buffers: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

# EBean Database 配置
spring:
  application:
    name: ZEUS-IOT
  datasource:
    druid:
      driver-class-name: org.postgresql.Driver
      username: ${ZEUS_DB_USERNAME:postgres}
      password: ${ZEUS_DB_PASSWORD:postgres}
      url: jdbc:postgresql://${ZEUS_DB_HOST:127.0.0.1}:${ZEUS_DB_PORT:5432}/zeus-iot
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  jackson:
    generator:
      write_numbers_as_strings: true

forest:
  variables:
    ## Zabbix API IP 和 端口
    zbxApiUrl: http://${ZEUS_ZABBIX_HOST:127.0.0.1}:${ZEUS_ZABBIX_PORT:80}/zabbix/api_jsonrpc.php
    zbxServerIp: ${ZEUS_ZABBIX_HOST:127.0.0.1}
    zbxServerPort: ${ZEUS_ZABBIX_PORT:80}
    zbxApiToken: 0fc68dae932f185a22901cd7d3f1ee55d70353ff03f2a2cdea795043aa4ca2a7

    ## 设备触发告警，执行动作回调 IOT-SERVER 处理
    zeusServerIp: ${ZEUS_CALLBACK_HOST:127.0.0.1}
    zeusServerPort: ${ZEUS_CALLBACK_PORT:9090}

  log-enabled: false
  timeout: 5000

logging:
  level:
    io.ebean: DEBUG